name: Deploy to Aliyun

on:
  push:
    branches:
      - main   # 推送到主分支时触发该工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.ALIYUN_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          HOST: ${{ secrets.ALIYUN_HOST }}
          USERNAME: ${{ secrets.ALIYUN_USERNAME }}
          PORT: ${{ secrets.ALIYUN_PORT }}
          PRIVATE_KEY: ${{ secrets.ALIYUN_PRIVATE_KEY }}
        run: |
          echo "${{ secrets.ALIYUN_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r dist/* $USERNAME@$HOST:/work/integration
          ssh -i private_key.pem $USERNAME@$HOST "sudo systemctl reload nginx"
          rm private_key.pem
